"""org-scoped api keys and project name uniqueness

Revision ID: 07b9d0dd685d
Revises: 74221852fb5a
Create Date: 2026-02-22 22:52:48.128706
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b9d0dd685d'
down_revision: Union[str, None] = '74221852fb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_project_org_name', 'projects', ['org_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_org_name', 'projects', type_='unique')
    op.alter_column('api_keys', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
