"""drop project_id from api_keys

Revision ID: 330472621252
Revises: 07b9d0dd685d
Create Date: 2026-02-22 23:02:39.381248
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330472621252'
down_revision: Union[str, None] = '07b9d0dd685d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_keys_project_id_fkey'), 'api_keys', type_='foreignkey')
    op.drop_column('api_keys', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('api_keys_project_id_fkey'), 'api_keys', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
