"""

Revision ID: 52c6571ebe12
Revises: 1a6a4ba593f5
Create Date: 2026-02-21 22:55:39.805442
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c6571ebe12'
down_revision: Union[str, None] = '1a6a4ba593f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organizations_slug_key'), 'organizations', type_='unique')
    op.drop_column('organizations', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('slug', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('organizations_slug_key'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
