"""add ondelete CASCADE to child FK columns

Revision ID: 74221852fb5a
Revises: 52c6571ebe12
Create Date: 2026-02-22 01:06:04.450275
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74221852fb5a'
down_revision: Union[str, None] = '52c6571ebe12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('evaluation_results_evaluation_id_fkey'), 'evaluation_results', type_='foreignkey')
    op.create_foreign_key(None, 'evaluation_results', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('evaluations_trace_id_fkey'), 'evaluations', type_='foreignkey')
    op.drop_constraint(op.f('evaluations_project_id_fkey'), 'evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'evaluations', 'traces', ['trace_id'], ['trace_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('spans_trace_id_fkey'), 'spans', type_='foreignkey')
    op.create_foreign_key(None, 'spans', 'traces', ['trace_id'], ['trace_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('traces_project_id_fkey'), 'traces', type_='foreignkey')
    op.create_foreign_key(None, 'traces', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traces', type_='foreignkey')
    op.create_foreign_key(op.f('traces_project_id_fkey'), 'traces', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'spans', type_='foreignkey')
    op.create_foreign_key(op.f('spans_trace_id_fkey'), 'spans', 'traces', ['trace_id'], ['trace_id'])
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('evaluations_project_id_fkey'), 'evaluations', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('evaluations_trace_id_fkey'), 'evaluations', 'traces', ['trace_id'], ['trace_id'])
    op.drop_constraint(None, 'evaluation_results', type_='foreignkey')
    op.create_foreign_key(op.f('evaluation_results_evaluation_id_fkey'), 'evaluation_results', 'evaluations', ['evaluation_id'], ['id'])
    # ### end Alembic commands ###
