"""add durable billing reports

Revision ID: fd38fefe55a8
Revises: 3ca1d40bddfa
Create Date: 2026-10-04 15:43:23.069956
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd38fefe55a8'
down_revision: Union[str, None] = '3ca1d40bddfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usage_record_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('closing_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('snapshot_trace_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_trace_eval_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_session_eval_count', sa.Integer(), nullable=False),
    sa.Column('pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempted_at', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stripe_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usage_record_id'], ['usage_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usage_record_id', 'closing_invoice_id', name='uq_billing_report_closure')
    )
    op.create_index('ix_billing_reports_status_created', 'billing_reports', ['status', 'created_at'], unique=False)
    op.create_index('ix_billing_reports_usage_record', 'billing_reports', ['usage_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_billing_reports_usage_record', table_name='billing_reports')
    op.drop_index('ix_billing_reports_status_created', table_name='billing_reports')
    op.drop_table('billing_reports')
    # ### end Alembic commands ###
